name: maya_ai
description: MAYA AI - Mental Health Assistant powered by Gemini Pro
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  flutter_svg: ^2.0.9
  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4

  # Gemini AI
  google_generative_ai: ^0.4.6

  # Utilities
  flutter_dotenv: ^5.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  crypto: ^3.0.6

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

